### ISSUE TITLE
Pact level items are gained again when reconnecting without restarting the game

### ISSUE THREAD

**Issue by littlemeowmeow0134** [NaixGames/Polycosmos#2]
When disconnecting and reconnecting, obtained pact levels are sent again. For example, if you've received 1 level of Routine Inspection, disconnecting and reconnecting will behave as if you've received 2, granting access to Greater Reflex. Restarting Hades and connecting normally once returns to normal.

To reproduce, disconnect and reconnect with the text client without restarting Hades.

**Comment by Naix99** [comment]
To complement the issue when I go back to the fix this: it also messes up with filler items.

It seems I am loading and storing information more than once when connecting and reconnecting; without clearing out obtained item information between connections

**Comment by NaixGames** [comment]
This should be fix on latest release :)
